#!/usr/bin/env python3
"""
Generate kusb_488b_firmware_data.h from a Windows KI-488 installation.

The KUSB-488B downloads an Altera FPGA bitstream and 8051 firmware on every
attach. Those images belong to Keithley/ADLINK and are not distributed with
darwin-gpib, so you build the header yourself from your own driver files --
the same arrangement linux-gpib uses for its gpib_firmware package.

You need two files from the KI-488 package (extract the installer with
`setup.exe /a` if it is not already installed):

    kusbgpib_fwdlx64.sys    holds the 8051 blobs
    USB-GPIB.RBF            the FPGA bitstream

Usage:
    tools/extract_kusb_firmware.py \
        --driver kusbgpib_fwdlx64.sys \
        --rbf    USB-GPIB.RBF \
        --out    driver/devices/kusb_488b/kusb_488b_firmware_data.h
"""

import argparse
import hashlib
import struct
import sys

# Blob locations in the x64 NT10 build of kusbgpib_fwdlx64.sys
# (Sep 2020, md5 4dca4ea6... for the main firmware). Each blob is a fixed
# buffer followed by a 32-bit length. Override with --extram-va / --main-va
# if you have a different build.
DEFAULT_EXTRAM_DATA_VA = 0x140007170
DEFAULT_EXTRAM_LEN_VA  = 0x140008170
DEFAULT_MAIN_DATA_VA   = 0x140008180
DEFAULT_MAIN_LEN_VA    = 0x14000C180


def load_pe_sections(data):
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\0\0":
        raise SystemExit("not a PE file")
    nsec = struct.unpack_from("<H", data, pe + 6)[0]
    optsz = struct.unpack_from("<H", data, pe + 20)[0]
    imgbase = struct.unpack_from("<Q", data, pe + 24 + 24)[0]
    secs = []
    for i in range(nsec):
        o = pe + 24 + optsz + i * 40
        vsz, va, rsz, ra = struct.unpack_from("<IIII", data, o + 8)
        secs.append((imgbase + va, rsz, ra))
    return secs


def va_to_off(secs, va):
    for base, rsz, ra in secs:
        if base <= va < base + rsz:
            return ra + (va - base)
    raise SystemExit(f"VA {va:#x} is not inside any section -- wrong driver build?")


def read_blob(data, secs, data_va, len_va, name):
    length = struct.unpack_from("<I", data, va_to_off(secs, len_va))[0]
    capacity = len_va - data_va
    if not (0 < length <= capacity):
        raise SystemExit(
            f"{name}: implausible length {length} (buffer capacity {capacity}); "
            "this is probably a different driver build -- pass explicit VAs")
    off = va_to_off(secs, data_va)
    return data[off:off + length]


def emit_array(out, symbol, blob):
    out.write(f"static const uint8_t {symbol}[] = {{\n")
    for i in range(0, len(blob), 12):
        row = ", ".join(f"0x{b:02X}" for b in blob[i:i + 12])
        out.write(f"    {row},\n")
    out.write("};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--driver", required=True, help="kusbgpib_fwdlx64.sys")
    ap.add_argument("--rbf", required=True, help="USB-GPIB.RBF")
    ap.add_argument("--out", required=True)
    ap.add_argument("--extram-va", type=lambda s: int(s, 0), default=DEFAULT_EXTRAM_DATA_VA)
    ap.add_argument("--extram-len-va", type=lambda s: int(s, 0), default=DEFAULT_EXTRAM_LEN_VA)
    ap.add_argument("--main-va", type=lambda s: int(s, 0), default=DEFAULT_MAIN_DATA_VA)
    ap.add_argument("--main-len-va", type=lambda s: int(s, 0), default=DEFAULT_MAIN_LEN_VA)
    args = ap.parse_args()

    drv = open(args.driver, "rb").read()
    rbf = open(args.rbf, "rb").read()
    secs = load_pe_sections(drv)

    extram = read_blob(drv, secs, args.extram_va, args.extram_len_va, "ext-RAM blob")
    main_fw = read_blob(drv, secs, args.main_va, args.main_len_va, "main firmware")

    # The 8051 images begin with LJMP (0x02). A mismatch means the offsets are
    # pointing at the wrong thing.
    if main_fw[:1] != b"\x02":
        raise SystemExit(
            f"main firmware does not start with 8051 LJMP (got {main_fw[0]:#04x}); "
            "offsets look wrong for this build")

    for name, blob in (("FPGA bitstream", rbf),
                       ("ext-RAM blob", extram),
                       ("main firmware", main_fw)):
        print(f"{name:16s} {len(blob):6d} bytes  md5={hashlib.md5(blob).hexdigest()}")

    with open(args.out, "w") as out:
        out.write("// Generated by tools/extract_kusb_firmware.py -- do not edit.\n")
        out.write("// Contains Keithley/ADLINK firmware images. Do not redistribute.\n\n")
        out.write("#ifndef kusb_488b_firmware_data_h\n")
        out.write("#define kusb_488b_firmware_data_h\n\n")
        out.write("#include <stdint.h>\n\n")
        emit_array(out, "kKusbFpgaBitstreamData", rbf)
        emit_array(out, "kKusbExtRamBlobData", extram)
        emit_array(out, "kKusbMainFirmwareData", main_fw)
        out.write("static const KUSBFirmwareBlob kKusbFpgaBitstream = "
                  "{ kKusbFpgaBitstreamData, sizeof(kKusbFpgaBitstreamData) };\n")
        out.write("static const KUSBFirmwareBlob kKusbExtRamBlob = "
                  "{ kKusbExtRamBlobData, sizeof(kKusbExtRamBlobData) };\n")
        out.write("static const KUSBFirmwareBlob kKusbMainFirmware = "
                  "{ kKusbMainFirmwareData, sizeof(kKusbMainFirmwareData) };\n\n")
        out.write("#endif /* kusb_488b_firmware_data_h */\n")

    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
